name: Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: '3.x'

# TODO: Need to figure out to remove a lot of this redunant definition between
# jobs, e.g., checkout, unpack, setup-node, do the thing, pack tarball, upload
# artifact. Composite action?
jobs:
  ContinuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Run Lint (Flake8)
        run: flake8 .
      - name: Run Unit Tests
        run: echo TODO 