name: Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: '20.x'

# TODO: Need to figure out to remove a lot of this redunant definition between
# jobs, e.g., checkout, unpack, setup-node, do the thing, pack tarball, upload
# artifact. Composite action?
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Create source tarball artifact
        run: tar -cf source.tar ./*
      - name: Upload source tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-checkout
          path: source.tar

  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Download source tarball
        uses: actions/download-artifact@v4
        with:
          name: source-checkout
      - name: Unpack source tarball
        run: tar -xf source.tar
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm' 
      - name: Run Lint
        run: npm run lint
    
  test:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Download source tarball
        uses: actions/download-artifact@v4
        with:
          name: source-checkout
      - name: Unpack source tarball
        run: tar -xf source.tar
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Run Unit Tests
        run: npm run test:unit 

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Download source tarball
        uses: actions/download-artifact@v4
        with:
          name: source-checkout
      - name: Unpack source tarball
        run: tar -xf source.tar
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Run Build
        run: npm run build
      - name: Create built tarball artifact
        run: tar -cf built.tar ./*
      - name: Upload built tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-built
          path: built.tar